### ISSUE TITLE
Add automatic delivery

### ISSUE THREAD

**Issue by lukasged** [TDAF/is-user-valid#12]
Until now, the is-user-valid was being deployed from within the [Telefónica Accounts](https://github.com/TDAF/accounts) project, but it should be an independent project with its own delivery.

- [x] Add High Availability with keepalived
- [x] Add loadbalancers with nginx (2 balancers)
- [x] Deploy is-user-valid instances (2 instances)
- [x] Request a public floating IP without TMG to be linked with the HA floating IP

**Comment by lukasged** [comment]
The ``192.168.137.247``floating IP from the ``ext_inet``network has been assigned for HA

**Comment by palmerabollo** [comment]
4 boxes for a 100-lines nodejs microservice. Hopefully our DCOS cluster will be ready soon.

![burning-money-cropped](https://cloud.githubusercontent.com/assets/673420/21191232/be09a730-c224-11e6-9378-921872e5b6a5.jpg)

**Comment by lukasged** [comment]
The public IP(with a firewall and without going through the TMG) `195.235.93.21` has been assigned for is-user-valid and the `accounts.tid.es` subdomain now points to the mentioned IP. 

The deployment in kilo is now up and ready 🎉
